SYNOS5D6 ; ven/gpl - generated sct2os5 data ;2026-03-15
 ;;0.7;VISTA SYN DATA LOADER;;Mar 18, 2025
 ;
 ; Generated by generate_synthea_os5_map.py
 ;
 q
 ;
DATA ; sct^os5^description
 ;;1290882004^2148P^History of seizure (situation)
 ;;1290953004^4742J^Plain X-ray of spine and pelvis (procedure)
 ;;1121000119107^5639K^Chronic neck pain (finding)
 ;;1151000175103^7665P^Dietary Approaches to Stop Hypertension diet (regime/therapy)
 ;;1171000175109^3247O^Increased physical activity (finding)
 ;;1231000119100^3659Q^History of aortic valve replacement (situation)
 ;;1501000119109^9352P^Proliferative diabetic retinopathy due to type II diabetes mellitus
 ;;1551000119108^5668Q^Nonproliferative diabetic retinopathy due to type II diabetes mellitus
 ;;1571000087109^6645Q^Ultrasonography of bilateral breasts (procedure)
 ;;60951000119105^0813N^Blindness due to type 2 diabetes mellitus (disorder)
 ;;67811000119102^0346H^Primary small cell malignant neoplasm of lung, TNM stage 1 (disorder)
 ;;67821000119109^8440L^Primary small cell malignant neoplasm of lung, TNM stage 2 (disorder)
 ;;67831000119107^9142L^Primary small cell malignant neoplasm of lung, TNM stage 3 (disorder)
 ;;67841000119103^2729P^Primary small cell malignant neoplasm of lung, TNM stage 4 (disorder)
 ;;90781000119102^7353I^Microalbuminuria due to type 2 diabetes mellitus (disorder)
 ;;97331000119101^9453H^Macular edema and retinopathy due to type 2 diabetes mellitus (disorder)
 ;;108631000119101^7617O^History of autologous bone marrow transplant (situation)
 ;;112001000119100^3048O^Positive screening for depression on Patient Health Questionnaire 9 (finding)
 ;;112011000119102^0283Q^Negative screening for depression on Patient Health Questionnaire 9 (finding)
 ;;119481000119105^2357K^History of aortic valve repair (situation)
 ;;120991000119102^0664O^History of undergoing in utero procedure while a fetus (situation)
 ;;124171000119105^3497H^Chronic intractable migraine without aura (disorder)
 ;;129721000119106^6342P^Acute renal failure on dialysis (disorder)
 ;;132281000119108^9204H^Acute deep venous thrombosis (disorder)
 ;;152621000119105^1530H^History of allotransplantation of bone marrow (situation)
 ;;153351000119102^4133K^History of peripheral stem cell transplant (situation)
 ;;157141000119108^9275H^Proteinuria due to type 2 diabetes mellitus (disorder)
 ;;368581000119106^4821J^Neuropathy due to type 2 diabetes mellitus (disorder)
 ;;371361000119107^6727L^Comprehensive metabolic panel (procedure)
 ;;428191000124101^6853L^Documentation of current medications
 ;;428211000124100^6120M^Assessment of substance use (procedure)
 ;;439101000124101^1473I^Easy to chew diet (regime/therapy)
 ;;439121000124106^3931O^Pureed diet (regime/therapy)
 ;;442571000124108^9101H^Tree nut (substance)
 ;;453131000124105^2574Q^Videotelephony encounter (procedure)
 ;;456191000124101^6487I^Postoperative care for dental procedure (regime/therapy)
 ;;755621000000101^8770J^Replacement of subcutaneous contraceptive
 ;;1015401000000102^6049Q^Fecal occult blood test
 ;;10939881000119105^3396I^Unhealthy alcohol drinking behavior (finding)
 ;;16602611000119108^1557J^Awaiting transplantation of lung (situation)
 ;;zzzzz
 ;
